---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Wait for Port 22
      wait_for:
        port: 22

    - name: Install dos2unix
      yum:
        name: dos2unix
        state: latest

    - name: Copy bash profile
      copy:
        src: /openvote/Deployment/appnode/filesToCopy/bash_profile
        dest: /root/.bash_profile
        owner: root
        group: root
        mode: 0644

    - name: Install Net Tools
      yum:
        name: net-tools
        state: latest

    - name: Install EPEL Repo
      yum:
        name: epel-release
        state: latest

    - name: Install tar
      yum:
        name: tar
        state: latest

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Install GIT
      yum:
        name: git
        state: latest

    - name: Install NPM
      yum:
        name: npm
        state: latest

    - name: GIT NVM
      git:
        repo: 'https://github.com/creationix/nvm.git'
        dest: /root/.nvm
        force: yes

    - name: chmod 700 nvm.sh
      file:
        path: /root/.nvm/nvm.sh
        mode: 700

    - name: NVM Install NodeJS
      shell: |
        source /root/.nvm/nvm.sh
        nvm install 6.9.2
        nvm alias default 6.9.2
      args:
        creates: /root/.nvm/alias
...
